server:
  http:
    addr: 0.0.0.0:8888
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9999
    timeout: 1s
data:
  database:
    driver: mysql
    dsn: root:dangerous@tcp(127.0.0.1:3306)/real_world
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
